### ISSUE TITLE
Error running Inveigh.exe 4.5

### ISSUE THREAD

**Issue by mubix** [Kevin-Robertson/Inveigh#34]
I'm not sure what might have gone wrong here:
```
Unhandled Exception: System.InvalidOperationException: Not listening. You must call the Start() method before calling this method.
   at System.Net.Sockets.TcpListener.BeginAcceptTcpClient(AsyncCallback callback, Object state)
   at Inveigh.HTTPListener.Start(IPAddress ipAddress, Int32 port, String type)
   at Inveigh.Control.<>c__DisplayClass3_11.<StartThreads>b__14()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unhandled Exception: System.InvalidOperationException: Not listening. You must call the Start() method before calling this method.
   at System.Net.Sockets.TcpListener.BeginAcceptTcpClient(AsyncCallback callback, Object state)
   at Inveigh.HTTPListener.Start(IPAddress ipAddress, Int32 port, String type)
   at Inveigh.Control.<>c__DisplayClass3_20.<StartThreads>b__19()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by jhainly** [comment]
I'm getting the same error @Kevin-Robertson. Any ideas?
